/** Intrinsic dimensions and blur placeholders for project photography. */
export type ImageMetadata = {
  width: number;
  height: number;
  blurDataURL?: string;
};

export const imageMetadata: Record<string, ImageMetadata> = {
  "/images/projects/avalon/form.jpeg": { width: 1206, height: 1591,
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoIAAsABUB8JYwAAlbNTHYAAPcnkUkhBbnGsqG+7EvSJtLMAAA=",
  },
  "/images/projects/avalon/formwork.jpeg": { width: 1206, height: 1591,
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoIAAsABUB8JYwAAlbNTHYAAPcnkUkhBbnGsqG+7EvSJtLMAAA=",
  },
  "/images/projects/avalon/hero.jpeg": { width: 5282, height: 4284,
  },
  "/images/projects/avalon/pour.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAABwAQCdASoIAAYABUB8JZwAApttyADNQ7J2Y1s24PYQOAAA",
  },
  "/images/projects/avalon/trowelling.jpeg": { width: 1206, height: 2122,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADQAQCdASoIAA4ABUB8JZwAApzsLM0wAADJx4jIsUjRh7wgAAA=",
  },
  "/images/projects/cove.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAACQAQCdASoIAAYABUB8JZQAAp1HJkgA/WbYJYAIEfy7gAAA",
  },
  "/images/projects/driveway.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADwAQCdASoIAAYABUB8JYgCdAD0pc7yXgAA+w6w/rSW9WaGFax/TgAA",
  },
  "/images/projects/footpath.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAACwAQCdASoIAAYABUB8JZQC7ADzd6SAAM0RKPFYNgdYQAAA",
  },
  "/images/projects/IMG_1477.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoIAAYABUB8JZQAAp2c/NmYAP7QviNQaRYazn+AAAA=",
  },
  "/images/projects/IMG_1481.jpeg": { width: 3024, height: 4032,
    blurDataURL: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoIAAsABUB8JZAC7ADbHQJxgAD7+fvylHDrQ1AR0N1gJdhA4wAAAA==",
  },
  "/images/projects/IMG_1644.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoIAAYABUB8JYwCdACg3cTgAPZRxqo94Q22S3tVp0/AAA==",
  },
  "/images/projects/IMG_5719.jpeg": { width: 5282, height: 4284,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADwAQCdASoIAAYABUB8JYwC7AEQ/iqC/QAAyUDVkR+engE4AAA=",
  },
  "/images/projects/me.jpeg": { width: 1206, height: 2622,
    blurDataURL: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAwCdASoIABEAPzmGuVOvKSWisAgB4CcJZTcAA3vAhoLiX5TcxwAA/izggi6OqgluOkYv5+cH7iiSxyetgAAA",
  },
  "/images/projects/narrabeen/done.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoIAAYABUB8JZQAAp2c/NmYAP7QviNQaRYazn+AAAA=",
  },
  "/images/projects/narrabeen/existing.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACQAQCdASoIAAYABUB8JYwAAlubOwAA80ku7yv0Qmvgpq8enjwAAA==",
  },
  "/images/projects/narrabeen/finish.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADQAQCdASoIAAYABUB8JZwAAp3SIAVqAAD+0F2Csb/T03sAAAA=",
  },
  "/images/projects/narrabeen/form.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAACQAQCdASoIAAYABUB8JZwAAuTqoAAA/XHB3PJQAAA=",
  },
  "/images/projects/narrabeen/garden.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAACQAQCdASoIAAYABUB8JZQAApYWdAAA/R32Avl5+NzIAA==",
  },
  "/images/projects/narrabeen/pour.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAABwAQCdASoIAAYABUB8JQAAU0t7aAD7nuVUjfWIx+ectgAA",
  },
  "/images/projects/pathway.jpeg": { width: 4032, height: 3024,
    blurDataURL: "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAACQAQCdASoIAAYABUB8JZwAApZHa4AA/BStD94sXVAAAA==",
  },
  "/images/projects/RenderedImage2.jpeg": { width: 1206, height: 2122,
    blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAA4ABUB8JQBOj+ACs8FTwAD+nsqfOsHioJwDeZ8+6RFWpbCMAAAA",
  },
  "/images/projects/sauna.jpeg": { width: 1206, height: 1837,
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoIAAwABUB8JaACsAEek6AA/sy/i0gGt7HNmxxCccnn0OPcAAA=",
  },
  "/images/projects/Seat.jpeg": { width: 5712, height: 4284,
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoIAAYABUB8JZgCdACBhYAA9mZPWVZz4sa5r1W+l6Ixj6NoAAA=",
  },
  "/images/projects/wall.jpeg": { width: 5712, height: 4284,
    blurDataURL: "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADQAQCdASoIAAYABUB8JZQC7AD0iz4oAADN9pci1hHJM1BMS4d4QAAA",
  },
  "/images/projects/zetland/form 2.jpeg": { width: 1206, height: 2088,
    blurDataURL: "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoIAA4ABUB8JZQAAurQ7YKAANyRLHwEjOySGkyXme3wgAAA",
  },
  "/images/projects/zetland/hero-poster.jpeg": { width: 1080, height: 1920,
    blurDataURL: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACQAQCdASoIAA4ABUB8JagAAppBhngA/nkkxkm4cG2lEQWWqg/xvKg0ewAAAA==",
  },
  "/images/projects/zetland/poured.jpeg": { width: 5712, height: 4284,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoIAAYABUB8JZwAAp1yiAQAAP4JpSwtTSXCwzgQAAA=",
  },
  "/images/projects/zetland/steel.jpeg": { width: 5712, height: 4284,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoIAAYABUB8JQBdgB5u8KAA/ZI7ahAu7H5ODaKTwAA=",
  },
  "/images/projects/zetland/top.jpeg": { width: 5712, height: 4284,
    blurDataURL: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACQAQCdASoIAAYABUB8JZwAApexCwAA9q/n3Bd5poTBBlyW4QAAAA==",
  },
};

export function getImageMetadata(src: string): ImageMetadata | undefined {
  const decoded = decodeURIComponent(src);
  return imageMetadata[decoded] ?? imageMetadata[src];
}
